import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from 'next/link'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="bg-gray-900 border-b border-gray-800">
          <div className="max-w-7xl mx-auto px-6 py-3 flex items-center justify-between">
            <div className="flex items-center gap-4">
              <Link href="/dashboard" className="text-indigo-400 font-bold">OrderForge</Link>
              <nav className="flex items-center gap-3">
                <Link href="/dashboard" className="text-gray-400 hover:text-white text-sm">Dashboard</Link>
                <Link href="/dashboard/clients" className="text-gray-400 hover:text-white text-sm">Clients</Link>
                <Link href="/dashboard/products" className="text-gray-400 hover:text-white text-sm">Products</Link>
                <Link href="/dashboard/inventory" className="text-gray-400 hover:text-white text-sm">Inventory</Link>
                <Link href="/dashboard/settings" className="text-gray-400 hover:text-white text-sm">Settings</Link>
              </nav>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
